//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kota
    {
        public kota()
        {
            this.mahasiswas = new HashSet<mahasiswa>();
        }
    
        public int KotaId { get; set; }
        public int NegaraId { get; set; }
        public string NamaKota { get; set; }
    
        public virtual negara negara { get; set; }
        public virtual ICollection<mahasiswa> mahasiswas { get; set; }
    }
}
