//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahasiswa
    {
        public string nim { get; set; }
        public Nullable<int> KotaId { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public Nullable<double> ipk { get; set; }
    
        public virtual kota kota { get; set; }
    }
}
