//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negara
    {
        public negara()
        {
            this.kotas = new HashSet<kota>();
        }
    
        public int NegaraId { get; set; }
        public string NamaNegara { get; set; }
    
        public virtual ICollection<kota> kotas { get; set; }
    }
}
